server:
  port: 20002

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.17.0.2:3308/finaltest
    username: root
    password: 1234
  devtools:
    livereload:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update

